
name: tutorial  
version: 1.0.0
config-version: 2

profile: tutorial 

model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [data]
macro-paths: [macros]
snapshot-paths: [snapshots]
log-path: "logs"
target-path: target  
clean-targets:  
  - target
  - dbt_modules

models:
  tutorial:
    marts:
      +materialized: table
