version: '3.8'

services:
  superset:
    build: .
    container_name: superset_app
    restart: always
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: 'DCXpM4EBG1H2o9WUsww4E3rWt5EjNzFjHpNUhxgiH_0='
      # Metadata DB (Superset internal DB)
      #SUPERSET_METADATA_DB_URI: 'mysql+mysqlclient://hust_2024:admin123@host.docker.internal:3308/hust_2024'
    volumes:
      - ./superset_home:/app/superset_home
      #- ./superset_config.py:/app/pythonpath/superset_config.py
    depends_on:
      - redis
    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin --username ${SUPERSET_USERNAME} --firstname ${SUPERSET_FIRSTNAME} --lastname ${SUPERSET_LASTNAME} --email ${SUPERSET_EMAIL} --password ${SUPERSET_PASSWORD} &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
